### ISSUE TITLE
Compiling SASS from parent

### ISSUE THREAD

**Issue by AlStar01** [JoshEllinger/JointsWP-child#3]
Hello, hope things are going well.

I'm having trouble compiling the foundation sass from the parent JointsWP theme folder. In a directory I have JointsWP and JointsWP-child. I was able to successfully use grunt-watch to compile custom sass from main.scss into main.css in JointsWP-child. The gruntfile.js remains unaltered and main.scss has @import 'settings'. 

Would you have any recommendations about best way in terms of workflow to compile the parent JointsWP scss? Would I want to @import 'style' from parent scss folder so that it compiles into main.css of child theme? Or would I want to set up a grunt file in the actual parent theme and grunt-watch & compile that inside there?

My goal is hopefully avoid adding unnecessary css for foundation elements like orbit and according which may not end up on my site. Also the compression ability of grunt would really help keep my files as small as possible.

I appreciate any advice you can provide. I've unfortunately been using a css version of JointsWP and absolutely love the work you put in to create this awesome child theme. I'm greatly looking forward to using this child theme on my next project.

Thanks!

**Comment by JoshEllinger** [comment]
you can import what you need using @import and the name of the file you need. (make sure jointsWP has the necessary sass files)

The gruntfile already knows the path to the SASS in JointsWP, so you can include any file in that folder via an import.
